### ISSUE TITLE
ToDo button has disappeared in latest update (on cozycloud.cc)

### ISSUE THREAD

**Issue by Terrycloth** [cozy/notes#46]
The ToDo button / check box is gone from Cozy Notes, so you can't mark lines as complete or incomplete. You can't see whether they've been marked as complete either.

I'm afraid this might be my fault, since I didn't test my code edits in PR #42 for the ToDo feature. But then, most of my code edits were in the stylesheets. I've looked over the `.styl` files again and I can't figure out what the problem would be.

**Comment by frankrousseau** [comment]
Sorry I didn't find time to check. I don't know when I'll be able to fix that.

**Comment by poupotte** [comment]
https://github.com/cozy/notes/commit/bd3dae0dbd8939ccf25c4a5fc6b4c01fa49c2b85 should fix this issue. @Terrycloth, have you still the problem ?

**Comment by Terrycloth** [comment]
I haven't had a chance to rebuild Cozy Notes on my local system, but things look the same at my cozycloud.cc -hosted account. Has the update been pushed to the Cozy app store yet?

**Comment by Terrycloth** [comment]
Okay, I've rebuilt Cozy Notes, and the ToDo button works again as it should. Thanks!

Now we just need to get that update on cozycloud.cc

**Comment by frankrousseau** [comment]
Great, thx @Terrycloth
