### ISSUE TITLE
Group notes in efficient way

### ISSUE THREAD

**Issue by Beast141** [cozy/notes#64]
Id like to bring this up as an enhancement maybe, it would really be nice if you were able to create groups and name them, and then inside those groups create notes. That would really be cool. unless this is already possible and i cannot find the option?

**Comment by aenario** [comment]
Hi @Beast141, you can already create a "sub-note", by clicking the small + which appears on the right of a Note. You can just use empty notes to serve as folder.

Does this feature meets your needs ?

**Comment by Beast141** [comment]
oh oky yes i see that now and it looks like it works just the same. Thanks.
